$(document).ready(function() {
	RandomGenerate();


function RandomGenerate(){
	var quotes = [
		'“Happy labor day... Enjoy it.”@Tweeted by Lakers small forward Metta World Peace on Memorial Day, 2012.',
		'“People think we make $3 million and $4 million a year. They don’t realize that most of us only make $500,000."@Pete Incaviglia, former Texas Rangers outfielder on why baseball players aren’t overpaid.',
		'“That’s part of the challenge of being a professional athlete.”@Former Houston Rockets backup center John Amaechi on not receiving a single minute of playing time during the season.',
		'“Hawaii doesn’t win many games in the United States.”@ESPN analyst Lee Corso on the University of Hawaii’s poor record against teams in mainland America.',
		'“Therapy can be a good thing; it can be therapeutic.”@Alex Rodriguez, New York Yankees third baseman.',
		'“The game was closer than the score indicated.”@MLB Hall of Fame pitcher Dizzy Dean after a 1-0 game.',
		'“Well, either side could win it, or it could be a draw.”@Ron Atkinson, former soccer player and television pundit.',
		'“I’m tellin’ ya man, to be able to stroke it like that must be some kind of feeling.”@Dick Vitale on J.J. Redick’s three-point shooting.',
		'Seattle Seahawks wide receiver Steve Largent explained which of his records he’ll cherish the most after retiring from football:@“Probably the Beatles’ White Album.”',
		'“I think that’s my biggest key in my workout... with swimming and weights... is like my weight room."@Ryan Lochte, Olympic swimmer and weight room appreciator.',
		'“Aw, how could he lose the ball in the sun? He’s from Mexico.”@Former Cubs announcer Harry Caray on Jorge Orta losing track of a fly ball.',
		'“It’s humbling being humble.”@Maurice Clarett, former Denver Broncos running back.',
		'“That’s all they said was wrong with me?”@Former heavyweight champ Mike Tyson responding to questions about him suffering from depression, low self-esteem and problems with anger management.',
		'“Saltwater taffy.”@Former NBA big man Caldwell Jones on his favorite seafood.',
		'“Why should we have to go to class if we came here to play FOOTBALL, we ain’t come to play SCHOOL, classes are POINTLESS.”@Tweet sent out by Ohio State backup quarterback Cardale Jones.',
		'“Chemistry is a class you take in high school or college, where you figure out two plus two is 10 or something.”@Dennis Rodman explaining team chemistry. ',
		'“It ain’t the heat. It’s the humility.”@Yankee legend Yogi Berra',
		'“It’s permanent, for now.”@Former MLB outfielder Roberto Kelly on whether or not he would change his nickname “Bobby” in the future. ',
		'“They throw [Dave] Winfield out at second—and he’s safe.”@San Diego Padres broadcaster Jerry Coleman',
		'“That picture was taken out of context.”@New York Mets pitcher Jeff Innis on a photo of him that he believed made him look goofy.',
		'“We’re leaving a big fat rail of coke and a shot of Jack for Santa this year... cookies and milk will just slow him down. #SimpleTruth”@Tweet by Patriots linebacker Brandon Spikes this past holiday season.',
		'“I guess that makes our biggest weakness lack of strength.”@Gene Stallings, Texas A&M football coach after hearing TCU head coach Abe Martin claim his team’s biggest strength is its lack of weakness.',
		'“I believe I am more intelligent than the average person. There are few people with such talent, so there are few able to judge what I am doing.”@Italian footballer Mario Balotelli on his past antics involving dart-throwing at youth league players and sneaking into a women’s prison.',
		'“You can sum up this sport in two words: You never know.”@Boxing trainer Lou Duva.',
		'After being asked what he had gotten out of his rookie season in the league, former MLB outfielder Hensley Meulens replied:@“Oh, $120,000.”',
		'“I just got caught up in the moment, and, oh well.”@U.S. snowboarder Lindsey Jacobellis to NBC’s Bob Costas. Jacobellis had just lost the 2006 gold medal for snowboardcross after botching a trick and falling down yards from the finish line.',
		'“I feel like I’m the best, but you’re not going to get me to say that.”@NFL legend Jerry Rice',
		'“Yo soy fiesta!”@Patriots tight end Rob Gronkowski in response to an ESPN Deportes reporter’s questions about how he plans to celebrate a win over the Baltimore Ravens.',
		'“They always put the smart guys out in right field. That’s where I used to play.”@Former MLB slugger Jose Canseco',
		'“I feel very Dominican.”@Alex Rodriguez on which nation he would play for in the first World Baseball Classic.',
		'“When you’re rich you don’t write checks... straight cash, homey.”@Randy Moss when asked how he’ll pay an NFL fine for unsportsmanlike celebration.',
		'Former Seattle SuperSonics center Jerome James explained his personal views on coach Nate McMillan calling him selfish with this little ditty:@“I don’t have the first clue who he is talking about, because all I worry about is Jerome.”',
		'“Gaylord Perry and Willie McCovey should know each other like a book. They’ve been ex-teammates for years now.”@Jerry Coleman, San Diego Padres broadcaster ',
		'“It was no Mozart.”@Bill Cowher after a tough victory on the gridiron. ',
		'“It may not impress you, but Holtz means ‘hard wood.’”@Former college football coach and television analyst Lou Holtz.',
		'“We must have had 99 percent of the match. It was the other three percent that cost us.”@Dutch soccer manager Ruud Gullit',
		'“Sam is an idiot—I-D-O-U-T—idiot.”@Shaquille O’Neal on Chicago Tribune writer Sam Smith, who wrote an article suggesting the Miami Heat rid themselves of "The Big Aristotle."',
		'“Don’t say I don’t get along with my teammates. I just don’t get along with some of the guys on my team.”@Former NFL wide receiver Terrell Owens',
		'“He’s the Man of the Hour, at this particular moment.”@Boxing promoter Don King',
		'Former San Francisco Giants coach Rocky Bridges was asked why he refused to eat snails, to which he responded:@“I prefer fast food.”',
		'“It’s going to be about me.”@Former NFL great Lawrence Taylor describing the autobiography he planned to write.',
		'“I’m not an athlete. I’m a professional baseball player.”@Former MLB first baseman and television analyst John Kruk',
		'“I’ve only scratched the iceberg.”@Tennis great Andre Agassi assessing his talent ceiling in 1990.',
		'After being asked about her love life during a promotional event for a line of undergarments she endorses, former tennis star Anna Kournikova had this to say:@“I’m not here to talk about my personal life. I’m here to talk about bras.” ',
		'After hearing an unproductive member of the team had been traded away, Philadelphia Phillies outfielder Lenny Dykstra reacted with:@“Great trade! Who did we get?”',
		'“Raise the urinals.”@Former backup shortstop Darrel Chaney’s advice on how the front office can keep the Braves on their toes. ',
		'“Michael Jordan is probably the greatest scorer to ever play in the game. But I may go so far to say LeBron James may be the greatest player to ever play the game.”@Scottie Pippen',
		'“Yankees pitchers have had great success against Cabrera when they get him out.”@Former MLB catcher and current sportscaster Tim McCarver',
		'“He might’ve won the war, but the battle’s not over.”@NFL running back Cadillac Williams on getting picked later in 2005 draft than his Auburn teammate Ronnie Brown.',
		'“The word genius isn’t applicable in football. A genius is a guy like Norman Einstein.”@Former Washington Redskins quarterback Joe Theisman',
		'“Ninety percent of this game is half mental.”@Yankess legend Yogi Berra',
		'“The only thing that keeps this organization from being recognized as one of the finest in baseball is wins and losses at the major league level."@Chuck Lamar, former Tampa Bay Devil Rays manager',
		'“What defines me? ...Ryan Lochte.”@Ryan Lochte, Olympic swimmer and horrendous interviewee',
		'“I’m traveling to all 51 states to see who can stop 85.”@Former NFL wide receiver Chad Johnson',
		'“My career was sputtering until I did a 360 and got headed in the right direction.”@Former Orlando Magic star Tracy McGrady',
		'“We’re going to turn this team around 360 degrees.”@New York Knicks guard Jason Kidd after being drafted by the Dallas Mavericks.',
		'“I’m rich. What am I supposed to do? Hide it?”@Former Detroit Tigers second baseman Lou Whitaker, after showing up to a players’ union meeting in a stretch limousine.',
		'“We’ll do all right if we can capitalize on our mistakes.”@Mickey Rivers, former MLB designated hitter',
		'“Sometimes they write what I say, not what I mean.”@Pedro Guerrero, former MLB baseball player',
		'“It’s war. They’re out there to kill you, so I’m out there to kill them. We don’t care about nobody but this U... I’m a soldier!”,@University of Miami tight end Kellen Winslow after a loss to Tennessee in 2003',
		'“I ain’t gonna be no escape-goat!”@NBA Hall of Famer Karl Malone',
		'Sportscaster Tim McCarver on increased home run rates in the MLB:@“It has not been proven, but I think it will be proven that the air is thinner now, there have been climactic changes over the last 50 years in the world, and I think that’s one of the reasons balls are carrying much better now than I remember.”',
		'“It’s not going to be peaches and gravy all the time.”@Former Indiana Pacers center Brad Miller showcasing an interesting palate when he described the team’s struggles to reporters. ',
		'“Son, looks to me like you’re spending too much time on one subject."@Former Texas A&M basketball coach Shelby Metcalf explaining what he told one of his players who received four F’s and one D on his report card.',
		'“Because there are no fours.”@Former NBA power forward Antoine Walker on why he shoots so many three-pointers.',
		'“I dunno. I never smoked any Astroturf."@Former Philly Tug McGraw on whether he preferred grass or Astroturf.',
		'“It’s almost like we have ESPN or something.”@Lakers great Magic Johnson on how he and teammate James Worthy always work so well together on the basketball court. ',
		'“Rice defends against the free throw as well as anybody I’ve seen.”@Former Texas A&M basketball coach Shelby Metcalf',
		'“I’ve got my family to feed.”@Former NBA swingman Latrell Sprewell on why he wanted to sign a contract extension or be traded after making $14.6 million during the 2004-05 season.',
		'"Surprise me.”@Yankees legend Yogi Berra on where his wife should bury him.',
		'"I PRAISE YOU 24/7!!!!!! AND THIS HOW YOU DO ME!!!!! YOU EXPECT ME TO LEARN FROM THIS??? HOW???!!! ILL NEVER FORGET THIS!! EVER!!! THX THO..."@Buffalo Bills wide receiver Stevie Johnson tweeted this message, presumably to the creator of the universe, after dropping a game-winning catch in 2010.',
		'“I may be dumb, but I’m not stupid.”@Former NFL great and current NFL analyst Terry Bradshaw.',
		'“He treats us like men. He lets us wear earrings.”@Former University of Houston wide receiver Torrin Polk on former coach John Jenkins',
		'Former MLB outfielder and base-stealing extraordinaire Rickey Henderson on a writer’s claim that 50 percent of major league baseball players use steroids:@“Well, I’m not one of them. So that’s 49 percent right there."',
		'“I’ve had to overcome a lot of diversity.”@Drew Gooden, Milwaukee Bucks forward-center',
		'“I’m very appreciative of being indicted.”@Former Florida State football coach Bill Peterson on being inducted into the Florida Hall of Fame.',
		'“I’m a four-wheel-drive pickup type of guy, and so is my wife.” @Former Red Sox outfielder Mike Greenwell',
		'When San Francisco Giants fans began chanting “Barry! Barry! Barry!” for Giants pitcher Barry Zito in Game 1 of the 2012 World series, broadcaster Joe Buck set up fellow sportscaster Tim McCarver for an easy home run:@“They used to say [Barry] for somebody else around here,” said Buck. “When Barry Manilow was playing in a concert,” replied McCarver. “Or Barry Bonds,” said Buck, incredulous.',
		'“Better make it six. I can’t eat eight.”@Former MLB pitcher Dan Osinski after a waitress asked him if he wanted his pizza cut into six slices or eight. ',
		'“I’m just happy that Jesus Christ did not let me lose my teeth when I was 20-years-old.”@Lakers small forward Metta World Peace when asked how his teammates were reacting to his name change.',
		'“I want to rush for 1,000 or 1,500 yards—whichever comes first.”@South Carolina Heisman Trophy winner George Rogers',
		'“We didn’t underestimate them. They were a lot better than we thought.”@Former English football manager Bobby Robson, on narrowly surviving a game against Cameroon in the 1990 World Cup.',
		'“They shouldn’t throw at me. I’m the father of five or six kids.”@Former MLB player Tito Fuentes on getting hit by pitches. ',
		'"There someone warming up in the bullpen, but he\'s obscured by his number."@Jerry Coleman, San Diego Padres broadcaster',
		'“He’s a guy who gets up at six o’clock in the morning regardless of what time it is.”@Lou Duva on the rigorous training regimen of heavyweight Andrew Golota.',
		'“I don’t think anyone on this team knows what ‘schism’ is, let alone could use it in a sentence. I thought it was an STD when I first heard it and was like ‘whoa, we preach abstinence in these parts.’"@Vikings defensive end Jared Allen said this about the possibility of a hostile “schism” growing in the locker room between teammates.',
		'“I owe a lot to my parents, especially my mother and father.”@Professional golfer Greg Norman',
		'“It isn’t like I came down from Mount Sinai with the tabloids.”@Former Indianapolis Colts head coach Ron Meyer, on whether or not he made the right decision by starting rookie quarterback Jeff George. ',
		'“I can shoot with my left hand, I can shoot with my right hand. I’m amphibious.”@Charles Shackleford, former NBA forward ',
		'Brother Ray Page, a teacher at St. Anthony High School in Jersey City, N.J., claims he once had to explain a geographical conundrum to his student, Bobby Hurley, who would go on to play for the Sacramento Kings:@“[Bobby Hurley] once asked me if Beirut was named after that famous baseball player who hit home runs.” ',
		'“We do the same things here.”@Former Chicago Bulls star Dennis Rodman on North Korean dictator Kim Jung Un using prison camps to punish alleged criminals. ',
		'“My sister’s expecting a baby, and I don’t know if I’m going to be an aunt or an uncle.”@NC State basketball player Chuck Nevitt explaining to his coach why he appeared nervous during practice.',
		'“Anyone with knowledge of the slave trade and the NFL could say that these two parallel each other.”@Pittsburgh Steelers running back Rashard Mendenhall tweeted this nugget of historical wisdom in 2011. ',
		'“I want all the kids to copulate me."@Chicago Cubs Hall of Famer Andre Dawson on being a role model for children.',
		'“Fade into Bolivian, I guess.”@Former heavyweight champ Mike Tyson on what he would do after retiring from boxing. ',
		'“We’re not attempting to circumcise the rules.”@Former Steelers head coach Bill Cowher ',
		'Never one to hold back on the crazy, Jose Canseco unleashed these dinosaur/physics related tweets on his followers earlier this month:@“Ancient gravity was much weaker..."“Gravity had to be weaker to make dinosaurs nimble.” ',
		'“The Bible never says anything about dinosaurs. You can\'t say there were dinosaurs when you never saw them. Someone actually saw Adam and Eve. No one ever saw a Tyrannosaurus Rex."@Former MLB outfielder Carl Everett', 
		'“The sun has been there for 500, 600 years.”@Former MLB outfielder Mike Cameron',
		'“I can’t really remember the names of the clubs that we went to.”@Shaquille O’Neal’s response to whether or not he had stopped at the Parthenon while in Greece.',
		];

    
		randomHilarity = quotes[Math.floor(Math.random()*quotes.length)];
    	Author=randomHilarity.split("@");
			$('.saying').text(Author[0]);
    		$('.speaker').text(Author[1]);
  		}
  
		  
		$(".button").on( "click", function() {
		    RandomGenerate();
		});  
		  
});